/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllenamentoRouteImport } from './routes/allenamento'
import { Route as AttivitaRouteImport } from './routes/attivita'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as FinanzeRouteImport } from './routes/finanze'
import { Route as NoteRouteImport } from './routes/note'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as StudioRouteImport } from './routes/studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllenamentoRoute = AllenamentoRouteImport.update({
  id: '/allenamento',
  path: '/allenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivitaRoute = AttivitaRouteImport.update({
  id: '/attivita',
  path: '/attivita',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzeRoute = FinanzeRouteImport.update({
  id: '/finanze',
  path: '/finanze',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allenamento': typeof AllenamentoRoute
  '/attivita': typeof AttivitaRoute
  '/calendario': typeof CalendarioRoute
  '/finanze': typeof FinanzeRoute
  '/note': typeof NoteRoute
  '/profilo': typeof ProfiloRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allenamento': typeof AllenamentoRoute
  '/attivita': typeof AttivitaRoute
  '/calendario': typeof CalendarioRoute
  '/finanze': typeof FinanzeRoute
  '/note': typeof NoteRoute
  '/profilo': typeof ProfiloRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allenamento': typeof AllenamentoRoute
  '/attivita': typeof AttivitaRoute
  '/calendario': typeof CalendarioRoute
  '/finanze': typeof FinanzeRoute
  '/note': typeof NoteRoute
  '/profilo': typeof ProfiloRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allenamento'
    | '/attivita'
    | '/calendario'
    | '/finanze'
    | '/note'
    | '/profilo'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allenamento'
    | '/attivita'
    | '/calendario'
    | '/finanze'
    | '/note'
    | '/profilo'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/allenamento'
    | '/attivita'
    | '/calendario'
    | '/finanze'
    | '/note'
    | '/profilo'
    | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllenamentoRoute: typeof AllenamentoRoute
  AttivitaRoute: typeof AttivitaRoute
  CalendarioRoute: typeof CalendarioRoute
  FinanzeRoute: typeof FinanzeRoute
  NoteRoute: typeof NoteRoute
  ProfiloRoute: typeof ProfiloRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allenamento': {
      id: '/allenamento'
      path: '/allenamento'
      fullPath: '/allenamento'
      preLoaderRoute: typeof AllenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivita': {
      id: '/attivita'
      path: '/attivita'
      fullPath: '/attivita'
      preLoaderRoute: typeof AttivitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanze': {
      id: '/finanze'
      path: '/finanze'
      fullPath: '/finanze'
      preLoaderRoute: typeof FinanzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllenamentoRoute: AllenamentoRoute,
  AttivitaRoute: AttivitaRoute,
  CalendarioRoute: CalendarioRoute,
  FinanzeRoute: FinanzeRoute,
  NoteRoute: NoteRoute,
  ProfiloRoute: ProfiloRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
